version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: lab6_nginx
    ports:
      - '8080:80'
    volumes:
      - ./www:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    container_name: lab6_php
    volumes:
      - ./www:/var/www/html
    depends_on:
      - redis
      - elasticsearch
      - clickhouse

  redis:
    image: redis:7-alpine
    container_name: lab6_redis
    ports:
      - '6379:6379'

  # Redis REST API (для HTTP доступа к Redis)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: lab6_redis_commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: lab6_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - '9200:9200'
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: lab6_clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  elastic_data:
  clickhouse_data:
